### ISSUE TITLE
NetLayers/100G-fpga-network-stack-core not accessible

### ISSUE THREAD

**Issue by EajksEajks** [Xilinx/xup_vitis_network_example#1]
Hi,

The NetLayers/100G-fpga-network-stack-core submodule is not accessible.
Is it a private repository ? With a BSD licence ?

Thx for any help,
Eric

**Comment by mariodruiz** [comment]
In the commit 9b02d4769163d164998b773ad6aecffe8eaa0685, I updated the submodule url to use https, that should solve the problem. 

The repository is public https://github.com/hpcn-uam/100G-fpga-network-stack-core/tree/master
