### ISSUE TITLE
How to see the GUI of cmac_kernel in VIVADO ?

### ISSUE THREAD

**Issue by zhuofanzhang** [Xilinx/xup_vitis_network_example#102]
Hi, I made some changes to cmac_kernel. I am wondering how can I see GUI of this kernel in VIVADO.

That is, how to see or generate the following figure. [https://github.com/Xilinx/xup_vitis_network_example/blob/7abfb86bdfa773fc6320b524e2b7b09b843190fa/img/cmac_kernel.png](url)

**Comment by mariodruiz** [comment]
Hi,

A Vivado project with the extension `.xpr` is generated within the folder `Ethernet`, so, you should be able to open it.

Mario

**Comment by zhuofanzhang** [comment]
> Hi,
> 
> A Vivado project with the extension `.xpr` is generated within the folder `Ethernet`, so, you should be able to open it.
> 
> Mario

Found it. Thanks.
