### ISSUE TITLE
About xilinx_u280_xdma_201920_3

### ISSUE THREAD

**Issue by pengjintao** [Xilinx/xup_vitis_network_example#106]
I'm using U280, vitis 2022.2, xilinx_u280_xdma_2022
I cannot find anywhere to download xilinx_u280_xdma_201920_3.
Could anybody share a development platform package to me (xilinx_u280_xdma_201920_3)?

**Comment by mariodruiz** [comment]
Hi @pengjintao,

The latest U280 platform is supported by VNx. The table is not updated yet.

Mario
