### ISSUE TITLE
Bug reported: name `ol` is not defined.

### ISSUE THREAD

**Issue by zhangchenqi123** [Xilinx/xup_vitis_network_example#108]
In `vnx-basic-image-transfer.ipynb` 
In section `Configure the application`
The `ol` is not defined.

![image](https://github.com/Xilinx/xup_vitis_network_example/assets/58100940/ab7dd6cd-435d-49da-822b-1b4eafd79909)

![image](https://github.com/Xilinx/xup_vitis_network_example/assets/58100940/c1e44a2f-7360-4e59-b0b2-b524119c0722)

This is the first time `ol`  has appeared here, and I haven't found where it is defined before.

**Comment by mariodruiz** [comment]
Hi @zhangchenqi123 

Thank you for reporting this.
It should be either `ol_w1` or `ol_w0` and then in the assignation they the object should be used appropriately. 

Would you be able to do a PR with the changes?

**Comment by zhangchenqi123** [comment]
Okay, I'd be happy to do this, but I'm fixing another bug. After I finish fixing it, I will do a PR.

**Comment by zhangchenqi123** [comment]
Aside from this issue, I've also come across another problem that I believe warrants opening a separate issue. I hope this doesn't inconvenience you in any way.

**Comment by mariodruiz** [comment]
can you please share here the changes you have attempted? 

Does any of the notebooks work?

**Comment by mariodruiz** [comment]
I think that portion should be replace with 

```python
mm2s_remote = ol_w1.krnl_mm2s_1
s2mm_local = ol_w0.krnl_s2mm_1

size = img_height * img_width * 3

if hasattr(ol_w1, 'HBM0'):
    s2mm_bank = ol_w0.HBM0
    mm2s_bank = ol_w1.HBM0
elif hasattr(ol, 'bank2'):
    s2mm_bank = ol_w0.bank1
    mm2s_bank = ol_w1.bank2
else:
    s2mm_bank = ol_w0.bank1
    mm2s_bank = ol_w1.bank1
```

**Comment by zhangchenqi123** [comment]
Ok, that works. Thanks a lot.
Besides, I found another bug in the last but one cell of this notebook.
![image](https://github.com/Xilinx/xup_vitis_network_example/assets/58100940/4e4c0580-2fbd-4a8e-a8e8-619f681a93ed)
It should be `tx`, because on the tx end, the bytes are 'out', on the rx end, the bytes are 'in'.
I will do a pr to modify this, too.
