### ISSUE TITLE
In branch `host_xrt`, the tx end can send the packets but the rx end keeps waiting.

### ISSUE THREAD

**Issue by zhangchenqi123** [Xilinx/xup_vitis_network_example#109]
First I run the rx end:
![image](https://github.com/Xilinx/xup_vitis_network_example/assets/58100940/49be2a4e-1c7c-4964-885b-ca9201ca851f)
Then I run the tx end:
![image](https://github.com/Xilinx/xup_vitis_network_example/assets/58100940/7f8bfedf-2168-46fe-8e0c-46a04ab604e4)
But the rx end is still waiting:
![image](https://github.com/Xilinx/xup_vitis_network_example/assets/58100940/7436610b-0f0a-425b-8891-d9642436af97)

On the tx end，I used `vnx_basic_if0.xclbin`,On the rx end, I used `vnx_basic_if1.xclbin`.
I have also tried to use `vnx_basic_if3.xclbin` on both tx end and rx end, but the results are the same: The rx end keeps waiting.

Two Alveo U280  FPGAs on two servers. The two FPGAs are directly connected.
I have successfully run the `vnx-benchmark-throughput.ipynb`. It shows the two FPGAs can send packets to each other.

Environment:
```
The OS of the two servers are  Ubuntu 18.04 and Ubuntu 20.04

The following version is the same on both servers：
Platform:  xilinx_u280_gen3x16_xdma_1_202211_1
Vitis: 2022.2
XRT Version:  2.14.354
```
Do you know the possible reason for this? I would appreciate any help you may provide.

**Comment by mariodruiz** [comment]
Hi @zhangchenqi123,

The branch you are referring to it is not longer supported. There are C++ APIs in the `master` branch.
