### ISSUE TITLE
Implement 100G TCP/IP Offload Engine on U250

### ISSUE THREAD

**Issue by HirunaVishwamith** [Xilinx/xup_vitis_network_example#119]
I have this repository, which is a 100G TOE. I want to know how to implement this on Alevo U250 and use this repository for 100G packet transfer.

[100G TOE](https://github.com/hpcn-uam/100G-fpga-network-stack-core)

This is the synthesized 100G TOE project using HLS.

![image](https://github.com/Xilinx/xup_vitis_network_example/assets/69134587/caf28e66-d90e-4db6-b1b2-0c7d11135d84)

**Comment by mariodruiz** [comment]
This project (repo) does not support TCP. I suggest you check out https://github.com/fpgasystems/Vitis_with_100Gbps_TCP-IP
