### ISSUE TITLE
Steps to build for xilinx_u250_gen3x16_xdma_3_1_202020_1 platform

### ISSUE THREAD

**Issue by mariodruiz** [Xilinx/xup_vitis_network_example#16]
The `xilinx_u250_gen3x16_xdma_3_1_202020_1` platform is only supported by Vitis 2020.2, however the network layer relies on Vivado HLS, which is deprecated in Vitis 2020.2. Therefore, to successfully build for this platform, you will need to use both Vitis 2020.1 and Vitis 2020.2.

These are the steps  I used to successfully reproduce the examples for this platform. Use XRT `2.8.743`

## Get a fresh copy of the repository 

Get the repository again and use it only to build for this platform. The goal is to avoid intermediate states

```sh
git clone https://github.com/Xilinx/xup_vitis_network_example.git --recursive vnx_u250
```

## Compile network layer

1. Source Vitis 2020.1 tools
2. `cd vnx_u250/NetLayers/`
3. Run make

```sh
make all DEVICE=<fullpath>/xilinx_u250_gen3x16_xdma_3_1_202020_1.xpfm
```

## Generate xclbin

After the network layer is compile, we can use Vitis 2020.2 to generate the xclbin

1. Source Vitis 2020.2 tools
2. Run `make`, from the root directory i.e. vnx_u250, to build the example as described [here](https://github.com/Xilinx/xup_vitis_network_example#generate-xclbin)

## Verify platform 

`xilinx_u250_gen3x16_xdma_3_1_202020_1` features the [two stage platform](https://xilinx.github.io/XRT/2020.2/html/platforms_partitions.html#two-stage-platforms), therefore you need to make sure that the partition is programmed before trying to download the xclbin file. [UG1301 Getting Started with Alveo Accelerator Cards](https://www.xilinx.com/support/documentation/boards_and_kits/accelerator-cards/1_8/ug1301-getting-started-guide-alveo-accelerator-cards.pdf) page 24 step 11

**Comment by HFTrader** [comment]
I can confirm this works for xilinx_u50_gen3x16_xdma_201920_3

**Comment by 6357o31337** [comment]
When I compile network layer (make all DEVICE=<fullpath>/xilinx_u250_gen3x16_xdma_3_1_202020_1.xpfm),
there was error
/bin/sh: 1: Syntax error: word unexpected (expecting ")")
Makefile:143: recipe for target 'check-design' failed
make: *** [check-design] Error 2

**Comment by 6357o31337** [comment]
When I 'Generate xclbin'(make all DEVICE=/opt/xilinx/platforms/xilinx_u250_gen3x16_xdma_3_1_202020_1/xilinx_u250_gen3x16_xdma_3_1_202020_1.xpfm INTERFACE=0 DESIGN=benchmark),

there are errors
/bin/sh: 1: Syntax error: word unexpected (expecting ")")
Makefile:143: recipe for target 'check-design' failed
make: *** [check-design] Error 2

How can I solve?

**Comment by mariodruiz** [comment]
@6357o31337, this seems to be an issue with the shell you're using.

If you run `ps -p $$` you will the shell you're using. For your info, I am using `bash`

```sh
bash --version
```
```
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by 6357o31337** [comment]
@mariodruiz , thank you.
Removing the 'check-design' and 'check-interface' targets helped me.

But when I try to 'Generate xclbin'(make all DEVICE=/opt/xilinx/platforms/xilinx_u250_gen3x16_xdma_3_1_202020_1/xilinx_u250_gen3x16_xdma_3_1_202020_1.xpfm INTERFACE=0 DESIGN=basic) again,
there is another error. (below imagaes)

How can I solve?

Thank you.

![image](https://user-images.githubusercontent.com/68189875/126434620-4b590fbe-b99c-428c-ad07-220f4ef93074.png)

...

![image](https://user-images.githubusercontent.com/68189875/126434669-877f3142-690d-4cd6-bfc9-4f178de07d51.png)


![image](https://user-images.githubusercontent.com/68189875/126434703-33195006-ee98-4caa-80e9-1ad5584d50f2.png)

**Comment by 6357o31337** [comment]
For more information,

![image](https://user-images.githubusercontent.com/68189875/126578839-44338e6c-54ba-4386-a02a-51027421d628.png)


Thank you.

**Comment by HFTrader** [comment]
I bet this is a memory issue. You got to add something like below in $HOME/.Xilinx/Vivado/Vivado_init.tcl

`set_param general.maxThreads 18`

**Comment by mariodruiz** [comment]
@6357o31337 if you still have the problem please:
- Open another issue and use the VNx issues template to provide the required information. 
 - Use [code snippets](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) to provide textual content instead of images.

**Comment by anipeg** [comment]
I got the same issue in Ubuntu.
That's because the Makefile default SHELL is /bin/sh.
I add "SHELL=/bin/bash" to Makefile first line and it work.
