### ISSUE TITLE
how a rtl-kernel connect the ethernet qsfp interface on vitis application projects.

### ISSUE THREAD

**Issue by csunclechen** [Xilinx/xup_vitis_network_example#21]
hello,
    I read your cmac ip bd and package files in the Ethernet folder.  the qsfp gt signals are showed on the top module of template_top.v. I am wondering about how these signals are Identified by the final vitis project like basic_kernel or benchmark_kernel, And how these signals are bound with physical pins as constraints. are the package_kernel.tcl, bd_cmac.tcl and template files written by yourself or auto-generated by vitis?
    Now I have a vitis application project using a rtl_kernel. the rtl_kernel need to communicate with another card through qsfp ethernet interface. I extract these qsfp gt signals on the top module of the rtl_kernel. But I don't know how the port connection between the vitis application project and rtl_kernel works.   
    Your project achieved the communication between two cards through qsfp ethernet by vitis software tool. I hope you can give me some advise about this. Thanks a lot.

**Comment by mariodruiz** [comment]
Hi @csunclechen,

How the GT pins are connected is described here https://github.com/Xilinx/xup_vitis_network_example#generate-xclbin 

The RTL kernels in this repository are generated manually based on the Vitis documentation https://www.xilinx.com/html_docs/xilinx2020_2/vitis_doc/devrtlkernel.html
