### ISSUE TITLE
Questions about gt_serial_port0

### ISSUE THREAD

**Issue by heiyiren1999** [Xilinx/xup_vitis_network_example#23]
Hello!
I build the project and find there is a bus-interface called "gt_serial_port0" in the component.xml file ("/Ethernet/packaged_kernel_cmac_0_xilinx_u280_xdma_201920_3/component.xml"). In the same .xml file, I also find other bus-interfaces (ap_clk, ap_rst_n, M_AXIS, S_AXIS, S_AXILITE). However, when I check the vivado.log ("/Ethernet/vivado.log"), I cannot find anything about "gt_serial_port0". I can only find something about other bus-interfaces which are shown in the image below.

![image](https://user-images.githubusercontent.com/32428729/113472083-311cb380-9493-11eb-84e3-c043c680b0f7.png)

So where can I check the generation of the bus-interface "gt_serial_port0"? I think that in this project, the bus-interface "gt_serial_port0" is generated by the tcl command ("/Ethernet/package_kernel.tcl") so there must be something printed as log. I know the component.xml verifies the existence of gt_serial_port0 but it's at a too late stage of the process. I want to check the log or something like that which is directly generated by package_kernel.tcl.

Thanks in advance!

**Comment by mariodruiz** [comment]
You could remove the `-notrace `from here https://github.com/Xilinx/xup_vitis_network_example/blob/master/Ethernet/Makefile#L74 and that will print everything.

I don't understand why you want that information, if the process to package to .xo takes only a few seconds.

**Comment by heiyiren1999** [comment]
My partner is more familiar with Vitis GUI and Wizard to generate RTL kernel. However, he meets the problem that he cannot generate bus-interface "gt_serial_port0" by editing package_kernel.tcl. So... can user generate their own bus-interface by editing package_kernel.tcl in Wizard? 

ps: I want to trace the generation of bus-interface "gt_serial_port0" in the xup project to support my partner's work, so I ask the previous question.

**Comment by mariodruiz** [comment]
Yes, it is possible to generate the gt_serial_port0 interface editing the tcl file. However, that is out of the scope of this repository and it is not recommended to do so for Vitis kernels.

**Comment by heiyiren1999** [comment]
OK. Thanks for your help! I'll recommand him to use Makefile.

**Comment by mariodruiz** [comment]
@heiyiren1999 , you can search for the Vivado project that generates the RTL kernel (`Ethernet/tmp_cmac_0_xilinx_u280_xdma_201920_3/kernel_pack.xpr`), you should be able to open it and edit there if necessary. But, this is something that I cannot support.
