### ISSUE TITLE
Can this example  be used to hardware emulation?

### ISSUE THREAD

**Issue by lijing1553** [Xilinx/xup_vitis_network_example#26]
I want to do some hardware emulation with XUP and my designed kernel. but when I set the target to hw_emu, I meet some errors. I want to know how I can get the emulation project in xup.
![截屏2021-04-30 下午5 39 26](https://user-images.githubusercontent.com/20725216/116677812-36f6ad80-a9db-11eb-8f35-dc2b54a657df.png)

**Comment by mariodruiz** [comment]
Hi @lijing1553,

Hardware emulation is something I have not tried, and there is no plan to work on it. If you work on it, we love your contribution with a PR.

If you go that route, I'd suggest to remove the cmac from the emulation and instead connect two network layers together.
Which part are you interested in emulating?

Mario
