### ISSUE TITLE
Timing failure in "Basic" design targeting U280

### ISSUE THREAD

**Issue by prajithrg** [Xilinx/xup_vitis_network_example#42]
Timing failure in XUP Vitis Network Example (VNx) project when we are trying to build the "basic" design targeting the U280. The error:

**********************************
 [13:31:18] Starting bitstream generation..
[13:36:54] Run vpl: Step impl: Failed
[13:36:55] Run vpl: FINISHED. Run Status: impl ERROR

===>The following messages were generated while  Compiling (bitstream) accelerator binary: vnx_basic_if0 Log file: xup_vitis_network_example/basic.intf0.xilinx_u280_xdma_201920_3/link/vivado/vpl/prj/prj.runs/impl_1/runme.log  :
ERROR: [VPL 101-2] design did not meet timing - Design did not meet timing. One or more unscalable system clocks did not meet their required target frequency. For all system clocks, this design is using 0 nanoseconds as the threshold worst negative slack (WNS) value. List of system clocks with timing failure:
system clock: txoutclk_out[0]; slack: -0.024 ns
ERROR: [VPL 101-3] sourcing script xup_vitis_network_example/basic.intf0.xilinx_u280_xdma_201920_3/link/vivado/vpl/scripts/_full_write_bitstream_pre.tcl failed
ERROR: [VPL 60-773] In xup_vitis_network_example/basic.intf0.xilinx_u280_xdma_201920_3/link/vivado/vpl/runme.log', caught Tcl error:  problem implementing dynamic region, impl_1: write_bitstream ERROR, please look at the run log file 'xup_vitis_network_example/basic.intf0.xilinx_u280_xdma_201920_3/link/vivado/vpl/prj/prj.runs/impl_1/runme.log' for more information
WARNING: [VPL 60-732] Link warning: No monitor points found for BD automation.
ERROR: [VPL 60-704] Integration error, problem implementing dynamic region, impl_1: write_bitstream ERROR, please look at the run log file 'xup_vitis_network_example/basic.intf0.xilinx_u280_xdma_201920_3/link/vivado/vpl/prj/prj.runs/impl_1/runme.log' for more information
ERROR: [VPL 60-1328] Vpl run 'vpl' failed
ERROR: [VPL 60-806] Failed to finish platform linker
INFO: [v++ 60-1442] [13:36:55] Run run_link: Step vpl: Failed
Time (s): cpu = 00:00:40 ; elapsed = 01:16:26 . Memory (MB): peak = 1984.984 ; gain = 0.000 ; free physical = 65482 ; free virtual = 101912
ERROR: [v++ 60-661] v++ link run 'run_link' failed
ERROR: [v++ 60-626] Kernel link failed to complete
ERROR: [v++ 60-703] Failed to finish linking
**********************************

The tool chain version we are using is 2021.1. Can you please let me know if am missing any frequency configuration or can you point me to any documentation on how to configure timing constraints for VNx project?

Please let me know in case of any clarifications. Looking forward to hear from you.

Thanks!
Best Regards
Prajith

**Comment by prajithrg** [comment]
Hi Mario,

The fix worked and the "vnx_basic_if0.xclbin" was successfully generated.

Thanks!
Best, Prajith

**Comment by mariodruiz** [comment]
For anyone else having this issue, now there a flag in the [Makefile](https://github.com/Xilinx/xup_vitis_network_example/blob/a8d8f1f54f34a4ab543c808737197406f5a68ea9/Makefile#L51) `kernel_frequency` which allows to specify a lower frequency for the kernels.
