### ISSUE TITLE
Question about the bandwidth tested in the Benchmark Throughput experiment (point to point)

### ISSUE THREAD

**Issue by LaceFern** [Xilinx/xup_vitis_network_example#50]
Hello. I find that in the Benchmark Throughput experiment (point to point), when the UDP payload size is 64B, the throughput is 55.538 Gbps. I calculate that when the UDP payload size is 64B, the sum of octets of the whole packet the CMAC IP generates  and octets of the interpacket gap is 8 + (46 + 64) + 12 = 130B according to the [Ethernet packet & IPG](https://en.wikipedia.org/wiki/Ethernet_frame) shown below. 

<img width="958" alt="1641267464(1)" src="https://user-images.githubusercontent.com/32428729/148006411-c3dbfdcf-460d-426d-ab09-1be154cbe81d.png">

Because the total theoretical line rate of the CMAC IP is 100 Gbps, the theoretical bandwidth for 64B udp payload should be 100 / 130 * 64 = 49 Gbps. I'm confused that the experimental bandwidth is higher than the theoretical bandwidth. Is there anything wrong in my analyses? Thanks for your help in advance!

**Comment by LaceFern** [comment]
I test the Layer 2 bandwidth with a naked CMAC IP and draw the picture below. I calculate the Layer 2 packet size (the size of the pink space about **Layer 2 Ethernet frame** in the pic. above) in your project, then use the formuler **UDP payload bandwidth / UDP payload size * Layer 2 packet size** to calculate the Layer 2 bandwidth of your project. The theoretical bandwidth is calculated by the formular **100 gbps / Layer 1 packet&IPG size * Layer 2 packet size**. Layer 1 packet&IPG size is the size of the pink space about **Layer 1 Ethernet packet & IPG** in the pic. above) 

<img width="466" alt="1641520900(1)" src="https://user-images.githubusercontent.com/32428729/148479444-c40b6633-2788-4093-9215-bb184c5edf0c.png">

More details are in the chart following.

<img width="757" alt="1641521460(1)" src="https://user-images.githubusercontent.com/32428729/148480097-bae2be8e-2186-4703-9a86-d5ca7a2894cd.png">

This problem obstructs my work so I'm concern about it. Thanks for your help in advance!

**Comment by LaceFern** [comment]
Sorry, I forgot to add 4B of CRC which is generated by CMAC into L2 Packet Size in Naked CMAC Bandwidth Test experiment. So the true experiment results are as below.

<img width="466" alt="1641532397(1)" src="https://user-images.githubusercontent.com/32428729/148495259-258be99b-d061-45c7-98cb-77a4f1f43be6.png">

<img width="760" alt="1641532446(1)" src="https://user-images.githubusercontent.com/32428729/148495335-0ae5f063-b90b-4d44-8486-a6947a702200.png">

**Comment by mariodruiz** [comment]
Hi,
You are right, I am not including the inter packet gap (12-Byte).

To compute the goodput at L2, you should count
- Inter-packet gap , 12-Byte
- Ethernet header, 14-Byte
- IP header, 20-Byte
- UDP header, 8-Byte

So, for a 64-Byte payload, the goodput is, 64/(64+12+14+20+8) = 64/118 = 0.5423. 54.23 Gbps it is a slightly slower than reported. I will double check this in the future.

How is this difference preventing your work?

**Comment by mariodruiz** [comment]
Hi,
You are right, I am not including the inter packet gap (12-Byte) nor the preamble and frame delimiter in my calculations. 
I need to look at this into more details.

How is this problem obstructing your work?

**Comment by LaceFern** [comment]
I need to implement network module with UDP protocol on my Vivado project for U280. 
At first, I used the network module in the Limago[https://github.com/hpcn-uam/Limago](url). However, I find the L2 bandwidth of this network module (the **orange** line with the legend **Vivado Udp** in the pic. below) is far lower than the theoretical bandwidth when the L2 Packet Size is small, namely, when the UDP payload is small.

<img width="663" alt="1641957293(1)" src="https://user-images.githubusercontent.com/32428729/149057589-60490290-0d94-4dd8-a4cc-4f98abbabee5.png">
<img width="332" alt="1641957404(1)" src="https://user-images.githubusercontent.com/32428729/149057758-613b4bc8-2d5b-4e16-91eb-a318be9e21cb.png">

However, in my work, the UDP payload is always small, so I need a network design with higher bandwidth for small UDP payload. That's the reason why I'm concern about this problem. 

I have tryed to read the code of Limago and yours but found it's hard to start with so many lines and files. I read the paper about Limago but it has little details about UDP. In fact, in my work, I don't need the whole TCP/IP stack but only functions about UDP. Would you like to offer some suggestions for me?  

Thanks in advance!

**Comment by mariodruiz** [comment]
There's an overhead for small packets that cannot be avoided with the current code. The Network layer is not optimized for small packets.

Limago is archived and not longer supported. 


If you want to improve the goodput for small packets, you will have to redesign the network layer completely. 
You can start with the [UDP code here](https://github.com/hpcn-uam/100G-fpga-network-stack-core/blob/vnx-vitis-hls/hls/UDP/udp.cpp). 

We do not have the bandwidth to support this, this repository is provided as-is and serves as an example or starting point only.

**Comment by IskandarZhang** [comment]
> 

Hello, The work you have done is very instructive to me, I also want to test a naked CMAC IP bandwidth to compare with this example project, I would be very grateful if you could give some guidance on how to carry out the test.

Best!

**Comment by mariodruiz** [comment]
The Xilinx® UltraScale+™ Devices Integrated 100G Ethernet IP subsystem provides a high-performance, low-latency 100 Gb/s
Ethernet port that allows for a wide range of user customization and statistics gathering. For more information refer to the user guide. https://www.xilinx.com/content/dam/xilinx/support/documentation/ip_documentation/cmac_usplus/v3_1/pg203-cmac-usplus.pdf 

There's always an overhead of adding any layer on top of the physical signals. You can compute this theoretically, no need to run any experiment.
