### ISSUE TITLE
How to change the size of send packets in 'vnx-benchmark-rtt.ipynb'?

### ISSUE THREAD

**Issue by IskandarZhang** [Xilinx/xup_vitis_network_example#51]
Hi Mario, after I downloaded the `.xclbin` file to my two U50 cards, I found that I can change the number of packets we used in application level via this code `send_package = xxx` in `vnx-benchmark-rtt.ipynb` benchmark program. But I did not realize how to change the size of each single package we sent in this program. Is this change avaliable? If yes, what corresponding code should I modify? 
Thank you in advance!

**Comment by mariodruiz** [comment]
Hi,

The packet size is set to 1408 in the mm2s kernel. If you want to change the packet size you will have regenerate the kernel and xclbin file after modifying the kernel.

**Comment by mariodruiz** [comment]
Apologies, my previous comment is valid for the basic application,

For the benchmark application you should be able to set the `number_beats`, this specifies the packet size in multiple of 64-Byte

**Comment by IskandarZhang** [comment]
> 

Hi, thanks for your clear and prompt reply in time when I was confusing. But the only sentence I found in the benchmark application related to `number_beats` is `ol_w0_tg.register_map.number_beats = 1` and how does it specifies the packet size in multiple of 64-Byte?  I would be grateful if you could give me some guidance on it. 
Best.

**Comment by IskandarZhang** [comment]
> Apologies, my previous comment is valid for the basic application,
> 
> For the benchmark application you should be able to set the `number_beats`, this specifies the packet size in multiple of 64-Byte

Hi, thanks for your clear and prompt reply in time when I was confusing. But the only sentence I found in the benchmark application related to number_beats is ol_w0_tg.register_map.number_beats = 1 and how does it specifies the packet size in multiple of 64-Byte? I would be grateful if you could give me some guidance on it.
Best.

**Comment by IskandarZhang** [comment]
> Apologies, my previous comment is valid for the basic application,
> 
> For the benchmark application you should be able to set the `number_beats`, this specifies the packet size in multiple of 64-Byte

Hi, thanks for your clear and prompt reply in time when I was confusing. But the only sentence I found in the benchmark application related to `number_beats` is `ol_w0_tg.register_map.number_beats = 1` and how does it specifies the packet size in multiple of 64-Byte? I would be grateful if you could give me some guidance on it.
Best.

**Comment by mariodruiz** [comment]
Check the vnx-benchmark-throughput-switch.ipynb notebook, the `beats`  is changed there.

The formula is easy,

pkt_size = beats * 64

**Comment by IskandarZhang** [comment]
> Check the vnx-benchmark-throughput-switch.ipynb notebook, the `beats` is changed there.
> 
> The formula is easy,
> 
> pkt_size = beats * 64
> 
> The reason for being multiple of 64-Byte is to simplify the hardware implementation and not to have to deal with the keep signal. If you want finer granularity, you will have to modify the `traffic_generator `

I'm sorry that I didn't fully understand your meaning. The notebook I'm testing is `vnx-benchmark-rtt.ipynb`, which doesn't seem to be related to ` vnx-benchmark-throughput-switch.ipynb` during the compilation. Do you mean to change the size of the sent packet by referring to the writing of the `beats` sentences in `vnx-benchmark-throughput-switch.ipynb`? 

I would like to know in which statement the sent packet size is defined in the `vnx-benchmark-rtt.ipynb` notebook if the statement exists and can be modified, which will help me to make changes.  

With your help I understood why the packet size is a multiple of 64 bytes and I don't consider it is needed for my experiment to modify the `traffic_generator` to get finer granularity. Actually I only need to know the size of the sending packet in the current notebook and how to modify the size of the sending packet in order to obtain different experimental data. 

Thanks in advance!

**Comment by mariodruiz** [comment]
The underlying hardware is the same for the notebook I mentioned, so you can take any code you want for any notebook that uses the same design.

If you want to change the packet size just do `ol_w0_tg.register_map.number_beats = size//64`

**Comment by IskandarZhang** [comment]
> The underlying hardware is the same for the notebook I mentioned, so you can take any code you want for any notebook that uses the same design.
> 
> If you want to change the packet size just do `ol_w0_tg.register_map.number_beats = size//64`

Hi Mario, when I change the packet size by modifying sentence `ol_w0_tg.register_map.number_beats = 1` in the notebook, I found that changes in `number_beats` don't seem to have an effect on the RTT time. In the process of changing `number_beats` from 1 to 24, the experimental results have not changed as shown below. 

`Round trip time at application level using 1,048,576 packets`
	`mean    = 1.147245 us`
	`std_dev = 0.003338 us`
	`mode    = 1.150000 us, which appears 420,235 times`
	`max     = 1.176667 us`
	`min     = 1.136667 us `

This situation is somewhat counterintuitive, I thought the experimental results would change as the packet size changes, I wonder if this is reasonable?  Thanks in advance!

**Comment by mariodruiz** [comment]
Typically, latency is measured with the smallest packet size for this reason in this implementation the latency computation does not take into consideration the packet size, the outgoing packets are stamped in the first 64-Byte as well as the incoming packets. Hence, the latency is constant regardless of the packet size. 

If you want to account for the packet size, you should modify the `segment_generator.v` file.

**Comment by IskandarZhang** [comment]
> Typically, latency is measured with the smallest packet size for this reason in this implementation the latency computation does not take into consideration the packet size, the outgoing packets are stamped in the first 64-Byte as well as the incoming packets. Hence, the latency is constant regardless of the packet size.
> 
> If you want to account for the packet size, you should modify the `segment_generator.v` file.

Thank you so much, Mario, I probably understand the reason for this design and I will close this issue with this comment.

**Comment by mariodruiz** [comment]
I would be good to have this feature, but it is something we are not currently planning on doing. You can contribute this change via a pull request.
