### ISSUE TITLE
Question about ethernet_remover function of packet_handler in Netlayer

### ISSUE THREAD

**Issue by IskandarZhang** [Xilinx/xup_vitis_network_example#55]
Hello Mario, I have some questions when I try to learn the data transmission process in packet_handler. Regardless of the ARP packets that must remain intact, the function of ethernet_remover is achieved by rearranging the order of output word. As the [code](https://github.com/hpcn-uam/100G-fpga-network-stack-core/blob/d56fd9f7e09527e800965ffd2b2961646d221cde/hls/packet_handler/packet_handler.cpp#L77) shows, it removed data of currWord.data(0, 111) as it is ethernet related. But I'm wondering whether this removing method will cause all stream data read later to be missing the first 14 bytes of data? 

A logical guess would be that ethernet_remover only works once for a complete ethernet frame, which guarantees that only 14 bytes of ethernet related content are removed, but I can't seem to find code that implements this functionality.

Thanks for your guidance in advance.

**Comment by mariodruiz** [comment]
Hi @IskandarZhang, every frame that is not ARP will get the ethernet header removed (14-Byte).  You  do not need a complete frame to take this decision, the ethertype field provides this information.

**Comment by IskandarZhang** [comment]
> Hi @IskandarZhang, every frame that is not ARP will get the ethernet header removed (14-Byte). You do not need a complete frame to take this decision, the ethertype field provides this information.

Hi Mario, thanks for your prompt reply. My understanding of your reply is that only the Ethernet-related part, or say the header , in a complete ethernet frame  is removed, and the rest remain intact, so it avoids the situation where every 512bit of data has to be removed by 14 bytes. Is my understanding correct?

Going a step further, how are the ethernet-removed data stitched back to their original location? And how is unprocessed data transmitted? I would be very appreciate if you could explain them, in conjunction with some specific code part would be more clear and better.

Thanks again!

**Comment by mariodruiz** [comment]
Only the first 14-Byte are removed. The full process is explained in the Limago paper and the paper that Limago is based upon.
