### ISSUE TITLE
Wrong cmake version on host_xrt code

### ISSUE THREAD

**Issue by mariodruiz** [Xilinx/xup_vitis_network_example#59]
@fpgafais the CMakeLists requires at least cmake 3.10, however  `target_link_directories` was not introduced until cmake 3.13 (https://cmake.org/cmake/help/latest/command/target_link_directories.html)

Is there any way to replace this functionality? Ubuntu 18.04 ships with cmake 3.10, and it is still has more than a year until EOL. So, it would be good not to require a cmake version newer than 3.10

**Comment by fpgafais** [comment]
@mariodruiz you are right, changed to link_directories for compatibility in #60
