### ISSUE TITLE
run benchmark notebook error

### ISSUE THREAD

**Issue by csunclechen** [Xilinx/xup_vitis_network_example#6]
![image](https://user-images.githubusercontent.com/26862588/100332891-eaaed800-300c-11eb-9252-ed4145a6f0b5.png)
Have you met this issue before? It seems that I can't use cmac ip.

**Comment by mariodruiz** [comment]
@csunclechen yes, this is a known issue on pynq 2.6.0. You either roll back to pynq 2.5.4 or apply these changes to the python files https://github.com/Xilinx/PYNQ/pull/1170/files
