### ISSUE TITLE
Does this repository support QDMA?

### ISSUE THREAD

**Issue by byeongkeonLee** [Xilinx/xup_vitis_network_example#80]
Hi, Mario. I always thank you for your kind reply.

I have a question about the QDMA of this project.

![image](https://user-images.githubusercontent.com/43103079/181429146-f6e90238-f14c-4816-b371-06a0126c549d.png)

In this figure, there is a word {X | Q}DMA for communication between PCIe and FPGA global memory. 

However, it seems that there is no official information about QDMA in this repository.

Could you let me know whether I can apply QDMA to this project, and if possible, how? (brief hints are appreciated!)

Best regards,

**Comment by mariodruiz** [comment]
Hi,

Good catch. I need to update the image.
QDMA platforms are not longer available. 

Mario

**Comment by byeongkeonLee** [comment]
Thank you for the quick reply, Mario!

I have one more question.

If you would not mind, I would like to know the brief reason QDMA is not available anymore.
(Because I'm still confused it is impossible due to a reason such as no Xilinx support)

Thank you!

**Comment by mariodruiz** [comment]
Well, the platforms are not supported anymore and they never were publicly available anyways. 
New features in the XDMA shells such as Host Memory Access are a good replacement for QDMA.

**Comment by byeongkeonLee** [comment]
I see!  Thank you!
