### ISSUE TITLE
[XRT] XRT related network performance (mm2s_buf.sync_to_device)

### ISSUE THREAD

**Issue by anonymous1782** [Xilinx/xup_vitis_network_example#82]
My question is about sync_to_device performance with this xup_vitis_network_example.

1. For a 100Gbps network through an Alveo card, the communication between host memory and FPGA memory needs to be 100Gbps, first.
In my experiment, however, mm2s_buf.sync_to_device() in jupyter notebook results in at most 75~85 Gbps, approximately.
If someone wants to use Alveo NIC through XRT, the mm2s_buf.sync_to_device() might be a bottleneck for data transfer.

2. Some benchmarks show about 95Gbps, but it is measured excluding host-FPGA data transfer. Consequently, I leave a question here about how to improve mm2s_buf.sync_to_device() throughput?

**Comment by mariodruiz** [comment]
Hi, 

1. You can run the `xbutil validate` to get the upper bound of the PCIe bandwidth.
2. VNx is not a NIC, none of the components is optimized to work as a NIC. This is stated in the main [README/Considerations](https://github.com/Xilinx/xup_vitis_network_example#considerations). If you want to use an Alveo card as a NIC please refer to the OpenNIC project.

Mario
