### ISSUE TITLE
Connecting U250 with Ethernet NIC using QSP fiber cable. 

### ISSUE THREAD

**Issue by karthickpython** [Xilinx/xup_vitis_network_example#88]
We are trying to have the entire packet processing inside FPGA(u250), So, that our application running in u250 can directly access remote access without the involvement of the Host.

our topology:
(U250 Qsp port) <-------> Qsp port ethernet LAN switch.

For above requirement, is Xup vitas suitable or anything else required?

**Comment by mariodruiz** [comment]
From the little information you are providing, I think VNx could work.

However, you should do your own investigation to understand if VNx is suitable.

**Comment by mariodruiz** [comment]
Closing as this is covered in the README. https://github.com/Xilinx/xup_vitis_network_example#faq
