### ISSUE TITLE
'cmac' object has no attribute '_call_struct'

### ISSUE THREAD

**Issue by heiyiren1999** [Xilinx/xup_vitis_network_example#9]
It's an amazing project and I want to implement it on my server. I follow your notebook to learn how to use it. However, when I run the **print("Link interface 0 {}; link interface 1 {}".format(ol.cmac_0.linkStatus(),ol.cmac_1.linkStatus()))**, it returned me an error that **'cmac' object has no attribute '_call_struct'**. The version of PYNQ on my server is 2.6.0, the operating system is 18.04 and the XRT is 202010.2.7.766_18.04-amd64-xrt (I think this error should not be related with the version of XRT). Now I don't know how to deal with this error. Would you like to give some advice? Thanks for any help!
![error](https://user-images.githubusercontent.com/32428729/105624107-1fe37500-5e5a-11eb-86af-ee9f052b7fff.png)

**Comment by heiyiren1999** [comment]
Oh, OK. I find that this error has been solved in one of the closed issues. 😂

**Comment by mariodruiz** [comment]
Yes, this is a known issue with the `pynq 2.6.0` version. For everyone's benefit the issue is solved here #6
