### ISSUE TITLE
How to test the PCIe bandwidth in the benchmark design?

### ISSUE THREAD

**Issue by IskandarZhang** [Xilinx/xup_vitis_network_example#91]
Hi Mario, long time. I noticed that only the throughput test between Kernels is involved in the Benchmark design. How should the bandwidth between CPU and FPGA, that is, PCIe bandwidth, be tested? Thanks.

**Comment by mariodruiz** [comment]
Hi @IskandarZhang,

This is the same question as `1` in here https://github.com/Xilinx/xup_vitis_network_example/issues/82

This is outside the scope of this project.
